#!/usr/bin/env bash
set -euo pipefail

APP_OWNER_USER="${APP_OWNER_USER:-octra-vitals-owner}"
APP_ROOT="${APP_ROOT:-/opt/octra-vitals}"
OWNER_DIR="${VITALS_OWNER_DATA_DIR:-/var/lib/octra-vitals-owner}"
ENV_DIR="${ENV_DIR:-/etc/octra-vitals}"
CURRENT="${APP_ROOT}/current"

if [ "$(id -u)" -ne 0 ]; then
  echo "deploy-programmed-circle.sh must run as root so updater.env can stay root-only" >&2
  exit 1
fi
if ! id "${APP_OWNER_USER}" >/dev/null 2>&1; then
  echo "missing cold-owner user: ${APP_OWNER_USER}; run bootstrap-host.sh first" >&2
  exit 1
fi

if [ ! -s "${ENV_DIR}/updater.env" ]; then
  echo "missing updater env: ${ENV_DIR}/updater.env" >&2
  exit 1
fi

cd "${CURRENT}"
. deploy/lib/env-file.sh

PROGRAM_OVERRIDE="${VITALS_PROGRAMMED_CIRCLE_PROGRAM:-}"
RECORD_VERSION_OVERRIDE="${VITALS_RECORD_SNAPSHOT_VERSION:-}"
ARTIFACT_DIR_OVERRIDE="${VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR:-}"
COMPILE_ARTIFACT_OVERRIDE="${VITALS_PROGRAMMED_CIRCLE_COMPILE_ARTIFACT:-}"
FACT_NETWORK_OVERRIDE="${VITALS_FACT_LEDGER_NETWORK_ID:-}"
FACT_PREDECESSOR_OVERRIDE="${VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM:-}"
FACT_PREDECESSOR_INDEX_OVERRIDE="${VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX:-}"
FACT_PREDECESSOR_ROOT_OVERRIDE="${VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT:-}"

load_env_file_data "${ENV_DIR}/updater.env"
load_env_file_data "${ENV_DIR}/owner.env"
unset VITALS_OPERATOR_PRIVATE_KEY_B64 OCTRA_PRIVATE_KEY_B64

if [ -n "${PROGRAM_OVERRIDE}" ]; then VITALS_PROGRAMMED_CIRCLE_PROGRAM="${PROGRAM_OVERRIDE}"; fi
if [ -n "${RECORD_VERSION_OVERRIDE}" ]; then VITALS_RECORD_SNAPSHOT_VERSION="${RECORD_VERSION_OVERRIDE}"; fi
if [ -n "${ARTIFACT_DIR_OVERRIDE}" ]; then VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR="${ARTIFACT_DIR_OVERRIDE}"; fi
if [ -n "${COMPILE_ARTIFACT_OVERRIDE}" ]; then VITALS_PROGRAMMED_CIRCLE_COMPILE_ARTIFACT="${COMPILE_ARTIFACT_OVERRIDE}"; fi
if [ -n "${FACT_NETWORK_OVERRIDE}" ]; then VITALS_FACT_LEDGER_NETWORK_ID="${FACT_NETWORK_OVERRIDE}"; fi
if [ -n "${FACT_PREDECESSOR_OVERRIDE}" ]; then VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM="${FACT_PREDECESSOR_OVERRIDE}"; fi
if [ -n "${FACT_PREDECESSOR_INDEX_OVERRIDE}" ]; then VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX="${FACT_PREDECESSOR_INDEX_OVERRIDE}"; fi
if [ -n "${FACT_PREDECESSOR_ROOT_OVERRIDE}" ]; then VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT="${FACT_PREDECESSOR_ROOT_OVERRIDE}"; fi

REPORT="${PROGRAMMED_CIRCLE_REPORT:-${OWNER_DIR}/programmed-circle-deploy.json}"
export VITALS_DEPLOY_PROGRAMMED_CIRCLE=1
export VITALS_DEPLOY_PROGRAMMED_CIRCLE_ACK=1

DEPLOY_ENV="$(mktemp)"
trap 'rm -f "${DEPLOY_ENV:-}"' EXIT
write_selected_env_file "${DEPLOY_ENV}" \
  OCTRA_PROGRAM_RPC_URL OCTRA_PROGRAM_RPC_URLS OCTRA_TX_RPC_URL OCTRA_RPC_URL \
  OCTRA_RPC_TIMEOUT_MS OCTRA_RPC_ATTEMPTS OCTRA_RPC_RETRY_DELAY_MS \
  OCTRA_RPC_MAX_CONCURRENT OCTRA_RPC_MIN_START_GAP_MS OCTRA_RPC_MAX_QUEUE \
  OCTRA_RPC_QUEUE_WAIT_MS OCTRA_RPC_MAX_RESPONSE_BYTES VITALS_GATEWAY_ROLE \
  VITALS_MIN_PROGRAM_RPC_URLS \
  VITALS_DEPLOY_PROGRAMMED_CIRCLE VITALS_DEPLOY_PROGRAMMED_CIRCLE_ACK \
  VITALS_DEPLOY_PROGRAMMED_CIRCLE_ALLOW_MAINNET VITALS_DEPLOY_WAIT \
  VITALS_REQUIRE_CONTRACT_RECEIPT VITALS_DEPLOYER_ADDRESS VITALS_INITIAL_OPERATOR_ADDRESS \
  VITALS_DEPLOYER_PRIVATE_KEY_B64 VITALS_PROGRAMMED_CIRCLE_ID VITALS_CIRCLE_VIEW_CALLER_ADDRESS \
  VITALS_PROGRAMMED_CIRCLE_PROGRAM VITALS_RECORD_SNAPSHOT_VERSION \
  VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR VITALS_PROGRAMMED_CIRCLE_COMPILE_ARTIFACT \
  VITALS_FACT_LEDGER_NETWORK_ID VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM \
  VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT \
  VITALS_PREDECESSOR_FROZEN_ACK VITALS_BREAK_GLASS_ROLE_COLLAPSE_ACK \
  VITALS_PREDECESSOR_PROGRAM VITALS_PREDECESSOR_FINAL_INDEX VITALS_PREDECESSOR_FINAL_ROOT \
  VITALS_PROGRAMMED_CIRCLE_SOURCE VITALS_ALLOW_PROGRAMMED_CIRCLE_ARTIFACT_DRIFT \
  VITALS_DEPLOY_CIRCLE_OU VITALS_PROGRAM_UPDATE_OU VITALS_CIRCLE_PROGRAM_UPDATE_OU \
  VITALS_INITIALIZE_CALL_OU VITALS_CALL_OU

sudo -u "${APP_OWNER_USER}" env -i \
  PATH="/usr/local/bin:/usr/bin:/bin" \
  HOME="${OWNER_DIR}" \
  bash --noprofile --norc -c '
  set -euo pipefail
  cd "$1"
  . deploy/lib/env-file.sh
  load_env_file_data /dev/stdin
  umask 077
  node dist/scripts/deploy-programmed-circle.js "$2"
' bash "${CURRENT}" "${REPORT}" < "${DEPLOY_ENV}"
