#!/usr/bin/env bash
set -euo pipefail

APP_OPERATOR_USER="${APP_OPERATOR_USER:-octra-vitals-operator}"
APP_ROOT="${APP_ROOT:-/opt/octra-vitals}"
DATA_DIR_DEFAULT="${VITALS_DATA_DIR:-/var/lib/octra-vitals}"
ENV_DIR="${ENV_DIR:-/etc/octra-vitals}"
CURRENT="${APP_ROOT}/current"

if [ "$(id -u)" -ne 0 ]; then
  echo "deploy-programmed-circle.sh must run as root so updater.env can stay root-only" >&2
  exit 1
fi

if [ ! -s "${ENV_DIR}/updater.env" ]; then
  echo "missing updater env: ${ENV_DIR}/updater.env" >&2
  exit 1
fi

cd "${CURRENT}"

PROGRAM_OVERRIDE="${VITALS_PROGRAMMED_CIRCLE_PROGRAM:-}"
RECORD_VERSION_OVERRIDE="${VITALS_RECORD_SNAPSHOT_VERSION:-}"
ARTIFACT_DIR_OVERRIDE="${VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR:-}"
FACT_NETWORK_OVERRIDE="${VITALS_FACT_LEDGER_NETWORK_ID:-}"
FACT_PREDECESSOR_OVERRIDE="${VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM:-}"
FACT_PREDECESSOR_INDEX_OVERRIDE="${VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX:-}"
FACT_PREDECESSOR_ROOT_OVERRIDE="${VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT:-}"

set -a
. "${ENV_DIR}/updater.env"
set +a

if [ -n "${PROGRAM_OVERRIDE}" ]; then VITALS_PROGRAMMED_CIRCLE_PROGRAM="${PROGRAM_OVERRIDE}"; fi
if [ -n "${RECORD_VERSION_OVERRIDE}" ]; then VITALS_RECORD_SNAPSHOT_VERSION="${RECORD_VERSION_OVERRIDE}"; fi
if [ -n "${ARTIFACT_DIR_OVERRIDE}" ]; then VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR="${ARTIFACT_DIR_OVERRIDE}"; fi
if [ -n "${FACT_NETWORK_OVERRIDE}" ]; then VITALS_FACT_LEDGER_NETWORK_ID="${FACT_NETWORK_OVERRIDE}"; fi
if [ -n "${FACT_PREDECESSOR_OVERRIDE}" ]; then VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM="${FACT_PREDECESSOR_OVERRIDE}"; fi
if [ -n "${FACT_PREDECESSOR_INDEX_OVERRIDE}" ]; then VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX="${FACT_PREDECESSOR_INDEX_OVERRIDE}"; fi
if [ -n "${FACT_PREDECESSOR_ROOT_OVERRIDE}" ]; then VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT="${FACT_PREDECESSOR_ROOT_OVERRIDE}"; fi

DATA_DIR="${VITALS_DATA_DIR:-${DATA_DIR_DEFAULT}}"
REPORT="${PROGRAMMED_CIRCLE_REPORT:-${DATA_DIR}/programmed-circle-deploy.json}"
export VITALS_DEPLOY_PROGRAMMED_CIRCLE=1
export VITALS_DEPLOY_PROGRAMMED_CIRCLE_ACK=1

sudo -u "${APP_OPERATOR_USER}" env \
  HOME="${DATA_DIR}" \
  OCTRA_PROGRAM_RPC_URL="${OCTRA_PROGRAM_RPC_URL:-}" \
  VITALS_DEPLOY_PROGRAMMED_CIRCLE="${VITALS_DEPLOY_PROGRAMMED_CIRCLE:-}" \
  VITALS_DEPLOY_PROGRAMMED_CIRCLE_ACK="${VITALS_DEPLOY_PROGRAMMED_CIRCLE_ACK:-}" \
  VITALS_DEPLOY_WAIT="${VITALS_DEPLOY_WAIT:-}" \
  VITALS_REQUIRE_CONTRACT_RECEIPT="${VITALS_REQUIRE_CONTRACT_RECEIPT:-}" \
  VITALS_DEPLOYER_ADDRESS="${VITALS_DEPLOYER_ADDRESS:-}" \
  VITALS_OPERATOR_ADDRESS="${VITALS_OPERATOR_ADDRESS:-}" \
  VITALS_INITIAL_OPERATOR_ADDRESS="${VITALS_INITIAL_OPERATOR_ADDRESS:-}" \
  VITALS_DEPLOYER_PRIVATE_KEY_B64="${VITALS_DEPLOYER_PRIVATE_KEY_B64:-}" \
  VITALS_OPERATOR_PRIVATE_KEY_B64="${VITALS_OPERATOR_PRIVATE_KEY_B64:-}" \
  OCTRA_PRIVATE_KEY_B64="${OCTRA_PRIVATE_KEY_B64:-}" \
  VITALS_PROGRAMMED_CIRCLE_ID="${VITALS_PROGRAMMED_CIRCLE_ID:-}" \
  VITALS_CIRCLE_VIEW_CALLER_ADDRESS="${VITALS_CIRCLE_VIEW_CALLER_ADDRESS:-}" \
  VITALS_PROGRAMMED_CIRCLE_PROGRAM="${VITALS_PROGRAMMED_CIRCLE_PROGRAM:-}" \
  VITALS_RECORD_SNAPSHOT_VERSION="${VITALS_RECORD_SNAPSHOT_VERSION:-}" \
  VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR="${VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR:-}" \
  VITALS_FACT_LEDGER_NETWORK_ID="${VITALS_FACT_LEDGER_NETWORK_ID:-}" \
  VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM="${VITALS_FACT_LEDGER_PREDECESSOR_PROGRAM:-}" \
  VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX="${VITALS_FACT_LEDGER_PREDECESSOR_FINAL_INDEX:-}" \
  VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT="${VITALS_FACT_LEDGER_PREDECESSOR_FINAL_ROOT:-}" \
  VITALS_PREDECESSOR_PROGRAM="${VITALS_PREDECESSOR_PROGRAM:-}" \
  VITALS_PREDECESSOR_FINAL_INDEX="${VITALS_PREDECESSOR_FINAL_INDEX:-}" \
  VITALS_PREDECESSOR_FINAL_ROOT="${VITALS_PREDECESSOR_FINAL_ROOT:-}" \
  VITALS_PROGRAMMED_CIRCLE_SOURCE="${VITALS_PROGRAMMED_CIRCLE_SOURCE:-}" \
  VITALS_ALLOW_PROGRAMMED_CIRCLE_ARTIFACT_DRIFT="${VITALS_ALLOW_PROGRAMMED_CIRCLE_ARTIFACT_DRIFT:-}" \
  VITALS_DEPLOY_CIRCLE_OU="${VITALS_DEPLOY_CIRCLE_OU:-}" \
  VITALS_PROGRAM_UPDATE_OU="${VITALS_PROGRAM_UPDATE_OU:-}" \
  VITALS_CIRCLE_PROGRAM_UPDATE_OU="${VITALS_CIRCLE_PROGRAM_UPDATE_OU:-}" \
  VITALS_INITIALIZE_CALL_OU="${VITALS_INITIALIZE_CALL_OU:-}" \
  VITALS_CALL_OU="${VITALS_CALL_OU:-}" \
  bash --noprofile --norc -lc "
  set -euo pipefail
  cd '${CURRENT}'
  npm run circle:programmed:deploy:dist -- '${REPORT}'
"
