#!/usr/bin/env bash
set -euo pipefail

APP_OWNER_USER="${APP_OWNER_USER:-octra-vitals-owner}"
APP_USER="${APP_USER:-octra-vitals}"
APP_ROOT="${APP_ROOT:-/opt/octra-vitals}"
OWNER_DIR="${VITALS_OWNER_DATA_DIR:-/var/lib/octra-vitals-owner}"
ENV_DIR="${ENV_DIR:-/etc/octra-vitals}"
CURRENT="${APP_ROOT}/current"

if [ "$(id -u)" -ne 0 ]; then
  echo "update-programmed-circle-code.sh must run as root so owner.env stays root-only" >&2
  exit 1
fi
if ! id "${APP_OWNER_USER}" >/dev/null 2>&1; then
  echo "missing cold-owner user: ${APP_OWNER_USER}; run bootstrap-host.sh first" >&2
  exit 1
fi

cd "${CURRENT}"
. deploy/lib/env-file.sh

UPDATE_OVERRIDE="${VITALS_UPDATE_PROGRAMMED_CIRCLE:-}"
ALLOW_MAINNET_OVERRIDE="${VITALS_UPDATE_PROGRAMMED_CIRCLE_ALLOW_MAINNET:-}"
ACK_OVERRIDE="${VITALS_PROGRAM_UPDATE_COMPATIBILITY_ACK:-}"
PREVIOUS_OVERRIDE="${VITALS_PROGRAM_UPDATE_PREVIOUS_COMPILE_ARTIFACT:-}"
COMPILE_OVERRIDE="${VITALS_PROGRAMMED_CIRCLE_COMPILE_ARTIFACT:-}"
SINGLE_PROGRAM_RPC_ACK_OVERRIDE="${VITALS_SINGLE_PROGRAM_RPC_MAINNET_ACK:-}"

load_env_file_data "${ENV_DIR}/updater.env"
load_env_file_data "${ENV_DIR}/owner.env"
unset VITALS_OPERATOR_PRIVATE_KEY_B64 OCTRA_PRIVATE_KEY_B64

if [ -n "${UPDATE_OVERRIDE}" ]; then VITALS_UPDATE_PROGRAMMED_CIRCLE="${UPDATE_OVERRIDE}"; fi
if [ -n "${ALLOW_MAINNET_OVERRIDE}" ]; then VITALS_UPDATE_PROGRAMMED_CIRCLE_ALLOW_MAINNET="${ALLOW_MAINNET_OVERRIDE}"; fi
if [ -n "${ACK_OVERRIDE}" ]; then VITALS_PROGRAM_UPDATE_COMPATIBILITY_ACK="${ACK_OVERRIDE}"; fi
if [ -n "${PREVIOUS_OVERRIDE}" ]; then VITALS_PROGRAM_UPDATE_PREVIOUS_COMPILE_ARTIFACT="${PREVIOUS_OVERRIDE}"; fi
if [ -n "${COMPILE_OVERRIDE}" ]; then VITALS_PROGRAMMED_CIRCLE_COMPILE_ARTIFACT="${COMPILE_OVERRIDE}"; fi
if [ -n "${SINGLE_PROGRAM_RPC_ACK_OVERRIDE}" ]; then VITALS_SINGLE_PROGRAM_RPC_MAINNET_ACK="${SINGLE_PROGRAM_RPC_ACK_OVERRIDE}"; fi

REPORT="${VITALS_PROGRAMMED_CIRCLE_UPDATE_OUT:-${OWNER_DIR}/programmed-circle-code-update.json}"
UPDATE_ENV="$(mktemp)"
trap 'rm -f "${UPDATE_ENV:-}"' EXIT
write_selected_env_file "${UPDATE_ENV}" \
  OCTRA_PROGRAM_RPC_URL OCTRA_PROGRAM_RPC_URLS OCTRA_TX_RPC_URL OCTRA_RPC_URL \
  OCTRA_RPC_TIMEOUT_MS OCTRA_RPC_ATTEMPTS OCTRA_RPC_RETRY_DELAY_MS \
  OCTRA_RPC_MAX_CONCURRENT OCTRA_RPC_MIN_START_GAP_MS OCTRA_RPC_MAX_QUEUE \
  OCTRA_RPC_QUEUE_WAIT_MS OCTRA_RPC_MAX_RESPONSE_BYTES VITALS_GATEWAY_ROLE \
  VITALS_PROGRAMMED_CIRCLE_ID VITALS_CIRCLE_VIEW_CALLER_ADDRESS \
  VITALS_CIRCLE_VIEW_MAX_CONCURRENT VITALS_CIRCLE_VIEW_MIN_START_GAP_MS \
  VITALS_CIRCLE_VIEW_MAX_QUEUE VITALS_CIRCLE_VIEW_QUEUE_WAIT_MS \
  VITALS_MIN_PROGRAM_RPC_URLS VITALS_FACT_LEDGER_NETWORK_ID \
  VITALS_PROGRAMMED_CIRCLE_ARTIFACT_DIR VITALS_PROGRAMMED_CIRCLE_SOURCE \
  VITALS_PROGRAMMED_CIRCLE_COMPILE_ARTIFACT VITALS_UPDATE_PROGRAMMED_CIRCLE \
  VITALS_UPDATE_PROGRAMMED_CIRCLE_ALLOW_MAINNET VITALS_DEPLOY_WAIT \
  VITALS_DEPLOYER_ADDRESS VITALS_DEPLOYER_PRIVATE_KEY_B64 \
  VITALS_PROGRAM_UPDATE_PREVIOUS_COMPILE_ARTIFACT VITALS_PROGRAM_UPDATE_COMPATIBILITY_ACK \
  VITALS_PROGRAM_UPDATE_OU VITALS_CIRCLE_PROGRAM_UPDATE_OU VITALS_SINGLE_PROGRAM_RPC_MAINNET_ACK
chown "${APP_OWNER_USER}:${APP_OWNER_USER}" "${UPDATE_ENV}"
chmod 600 "${UPDATE_ENV}"

sudo -u "${APP_OWNER_USER}" env -i \
  PATH="/usr/local/bin:/usr/bin:/bin" \
  HOME="${OWNER_DIR}" \
  bash --noprofile --norc -c '
  set -euo pipefail
  cd "$1"
  . deploy/lib/env-file.sh
  load_env_file_data "$3"
  export VITALS_PROGRAMMED_CIRCLE_UPDATE_OUT="$2"
  umask 077
  node dist/scripts/update-programmed-circle-code.js
' bash "${CURRENT}" "${REPORT}" "${UPDATE_ENV}"

DATA_DIR="${VITALS_DATA_DIR:-/var/lib/octra-vitals}"
install -d -m 750 -o root -g "${APP_USER}" "${DATA_DIR}/deployment-runs"
node dist/scripts/archive-deploy-spend-report.js \
  --kind program_update \
  --report "${REPORT}" \
  --out-dir "${DATA_DIR}/deployment-runs" || echo "warning: program update spend archival failed" >&2
chgrp -R "${APP_USER}" "${DATA_DIR}/deployment-runs" || true
chmod -R g+rX "${DATA_DIR}/deployment-runs" || true
